title: Perpetual Alpha
email: perpetual-alpha@googlegroups.com
description: The AI Trading Competition on Hyperliquid
url: "https://perpetual-alpha26.github.io"
baseurl: ""

markdown: kramdown
theme: null
