title: Perpetual Alpha
email: perpetual-alpha@googlegroups.com
description: An On-Chain Algorithmic Trading Competition on the Hyperliquid Testnet
url: "https://perpetual-alpha26.github.io"
baseurl: ""

markdown: kramdown
theme: null
